### ISSUE TITLE
Script freezes autokey-gtk 

### ISSUE THREAD

**Issue by squizzi** [squizzi/grabh1#1]
`autokey-gtk -l` output shows:
~~~
/usr/lib/python2.7/site-packages/bs4/__init__.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 777 of the file /usr/lib64/python2.7/threading.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "lxml")

  markup_type=markup_type))
2017-03-08 11:44:33,716 ERROR - service - Script error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/autokey/service.py", line 453, in execute
    exec script.code in scope
  File "<string>", line 14, in <module>
  File "/usr/lib/python2.7/site-packages/autokey/scripting.py", line 42, in send_keys
    self.mediator.send_string(keyString.decode("utf-8"))
AttributeError: 'NoneType' object has no attribute 'decode'
Exception in thread Phrase-thread:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 804, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 757, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/autokey/service.py", line 463, in execute
    self.app.notify_error(_("The script '%s' encountered an error") % script.description)
  File "/usr/lib/python2.7/site-packages/autokey/gtkapp.py", line 230, in notify_error
    self.notifier.notify_error(message)
  File "/usr/lib/python2.7/site-packages/autokey/gtkui/notifier.py", line 145, in notify_error
    self.show_notify(message, Gtk.STOCK_DIALOG_ERROR)
  File "/usr/lib/python2.7/site-packages/autokey/gtkui/notifier.py", line 160, in show_notify
    n.attach_to_status_icon(self.icon)
AttributeError: 'Notification' object has no attribute 'attach_to_status_icon'
~~~

**Comment by squizzi** [comment]
So the notify code inside autokey doesn't even appear to work, and `notify_error` can't fire correctly.  Still, the issue with the actual script code is here in `send_keys`:

~~~
2017-03-08 11:44:33,716 ERROR - service - Script error
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/autokey/service.py", line 453, in execute
    exec script.code in scope
  File "<string>", line 14, in <module>
  File "/usr/lib/python2.7/site-packages/autokey/scripting.py", line 42, in send_keys
    self.mediator.send_string(keyString.decode("utf-8"))
~~~
